### ISSUE TITLE
ES6 features break browserify older Node.js support

### ISSUE THREAD

**Issue by thlorenz** [bendrucker/test-peer-range#8]
Hey, just a quick note that browserify-shim support for older Node.js versions is affected by use of destructuring in this module.
Noticed when adding github sponsor button.

We could just drop older Node.js support in browserify-shim or lock the version of this module.

[build link](https://travis-ci.org/thlorenz/browserify-shim/builds/549769198)

**Comment by bendrucker** [comment]
This module now requires node 8 as of version 2, I'll just back-port a fix removing the destructuring on 1.

**Comment by bendrucker** [comment]
Actually seems like there are quite a few things to back out via dependencies, probably makes more sense to pin and then eventually drop support for old node versions.
